main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.18"
author: AUTHOR
description: DESCRIPTION
commands:
  ytstream:
    description: Manage the YouTube chat bridge
    usage: "/ytstream <setchat|settarget|reload>"
    aliases: [yt]
    permission: example.ytstream.use
    permission-message: "You do not have permission to manage the YouTube stream integration."
  ttstream:
    description: Manage the TikTok chat bridge
    usage: "/ttstream <setchat|settarget|reload>"
    aliases: [tt]
    permission: example.ttstream.use
    permission-message: "You do not have permission to manage the TikTok stream integration."
  nightpunish:
    description: Curse a player with eternal night and periodic deaths
    usage: "/nightpunish <start|stop> <player> [minutes]"
    permission: example.nightpunish.use
    permission-message: "You do not have permission to wield the night curse."
permissions:
  example.ytstream.use:
    description: Allows managing the YouTube stream chat bridge
    default: op
  example.ytstream.monitor:
    description: Allows receiving chat messages from the YouTube bridge
    default: true
  example.ttstream.use:
    description: Allows managing the TikTok stream chat bridge
    default: op
  example.ttstream.monitor:
    description: Allows receiving chat messages from the TikTok bridge
    default: true
  example.nightpunish.use:
    description: Allows casting the eternal night punishment on players
    default: op
