main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21"
author: AUTHOR
description: DESCRIPTION
commands:
  ytstream:
    description: Manage the YouTube chat bridge
    usage: "/ytstream <setchat|settarget|reload>"
    aliases: [yt]
    permission: example.ytstream.use
    permission-message: "You do not have permission to manage the YouTube stream integration."
permissions:
  example.ytstream.use:
    description: Allows managing the YouTube stream chat bridge
    default: op
  example.ytstream.monitor:
    description: Allows receiving chat messages from the YouTube bridge
    default: true
